# Generated by Django 2.2.22 on 2021-05-26 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='area_moveis',
            field=models.CharField(choices=[('Quarto', 'Quarto'), ('Cozinha', 'Cozinha'), ('Escritorio', 'Escritorio'), ('Sala', 'Sala'), ('Area-de-servico', 'Area-de-servico'), ('Externo', 'Externo'), ('Usados', 'Usados'), ('Outro', 'Outro')], default='Sem-area', max_length=60),
        ),
        migrations.AlterField(
            model_name='produto',
            name='marca',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='produto',
            name='tipo',
            field=models.CharField(choices=[('Guarda-roupa', 'Guarda-roupa'), ('Armario', 'Armario'), ('Mesa', 'Mesa'), ('Cadeira', 'Cadeira'), ('Rack', 'Rack'), ('Painel', 'Painel'), ('Cristaleira', 'Cristaleira'), ('Estante', 'Estante'), ('Fruteira', 'Fruteira'), ('Sapateira', 'Sapateira'), ('Balcão', 'Balcão'), ('Paneleiro', 'Paneleiro'), ('Cama', 'Cama'), ('Outro', 'Outro')], default='Sem-tipo', max_length=60),
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
        migrations.DeleteModel(
            name='Marca',
        ),
    ]
