# Generated by Django 2.2.22 on 2021-05-27 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0002_auto_20210526_2035'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='disponiveis',
            field=models.IntegerField(default=0),
        ),
    ]
