# Generated by Django 2.2.22 on 2021-05-29 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0003_produto_disponiveis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='photo1',
            field=models.ImageField(blank=True, null=True, upload_to='products_photos/'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='photo2',
            field=models.ImageField(blank=True, null=True, upload_to='products_photos/'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='photo3',
            field=models.ImageField(blank=True, null=True, upload_to='products_photos/'),
        ),
    ]
