# Generated by Django 2.2.22 on 2021-05-29 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(max_length=11)),
                ('rg', models.CharField(max_length=9)),
                ('image_cpf', models.ImageField(blank=True, null=True, upload_to='documents/')),
                ('image_rg', models.ImageField(blank=True, null=True, upload_to='documents/')),
                ('nome_completo', models.CharField(max_length=100)),
                ('telefone', models.CharField(max_length=11)),
                ('pis_pasep', models.CharField(max_length=100)),
                ('numero_serie_ctps', models.CharField(max_length=100)),
                ('data_admissao', models.DateField()),
                ('funcao', models.CharField(max_length=100)),
                ('jornada_de_trabalho', models.IntegerField()),
                ('status', models.CharField(choices=[('Ativo', 'ativo'), ('Licenciado', 'licenciado'), ('Ferias', 'ferias'), ('Desligado', 'desligado')], max_length=100)),
                ('horas_trabalhadas', models.DecimalField(decimal_places=2, max_digits=10)),
                ('horas_extras', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_pagamento', models.DateField()),
            ],
        ),
    ]
