# Generated by Django 2.2.22 on 2021-05-30 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funcionario',
            name='data_pagamento',
        ),
        migrations.AddField(
            model_name='funcionario',
            name='dia_pagamento',
            field=models.CharField(default='10', max_length=100),
        ),
    ]
