# Generated by Django 2.2.22 on 2021-05-25 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adicionais',
            name='nome_completo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
