# Generated by Django 2.2.22 on 2021-05-28 16:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0002_adicionais_nome_completo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adicionais',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
