# Generated by Django 2.2.22 on 2021-06-02 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vendas', '0009_auto_20210602_1917'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entrega',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previsao', models.DateField()),
                ('frete', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('venda', models.ManyToManyField(to='vendas.Vendas')),
            ],
        ),
    ]
