# Generated by Django 2.2.22 on 2021-06-02 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entregas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrega',
            name='horario',
            field=models.TimeField(default='00:00'),
        ),
        migrations.AddField(
            model_name='entrega',
            name='montagem',
            field=models.CharField(choices=[('S', 'Sim'), ('N', 'Nao')], default='N', max_length=3),
        ),
    ]
