# Generated by Django 2.2.22 on 2021-06-03 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entregas', '0003_auto_20210603_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrega',
            name='endereco_completo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
