# Generated by Django 2.2.22 on 2021-06-02 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0004_auto_20210529_1247'),
        ('vendas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vendas',
            options={},
        ),
        migrations.AddField(
            model_name='vendas',
            name='produto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='estoque.Produto'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vendas',
            name='quantidade',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ItemDoPedido',
        ),
    ]
