# Generated by Django 2.2.22 on 2021-06-02 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0002_auto_20210602_1256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendas',
            name='desconto',
        ),
        migrations.RemoveField(
            model_name='vendas',
            name='impostos',
        ),
    ]
