# Generated by Django 2.2.22 on 2021-06-02 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0004_auto_20210602_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendas',
            name='numero',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
