# Generated by Django 2.2.22 on 2021-06-02 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0005_auto_20210602_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendas',
            name='produto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='estoque.Produto'),
        ),
    ]
