# Generated by Django 2.2.22 on 2021-06-02 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0007_auto_20210602_1807'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendas',
            old_name='nome',
            new_name='nome_completo',
        ),
    ]
