# Generated by Django 2.2.22 on 2021-06-02 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0008_auto_20210602_1809'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vendas',
            options={'verbose_name_plural': 'Vendas'},
        ),
    ]
