# Generated by Django 2.2.22 on 2021-06-03 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0009_auto_20210602_1917'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendas',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vendas',
            name='telefone',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
